<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="54733" started-at="2022-11-14T06:48:59Z" finished-at="2022-11-14T06:49:54Z">
    <groups>
      <group name="groupname1">
        <method signature="Sample.homePageDisplayed()[pri:0, instance:test.script.Sample@32c4e8b2]" name="homePageDisplayed" class="test.script.Sample"/>
      </group> <!-- groupname1 -->
    </groups>
    <test name="Chrome" duration-ms="54733" started-at="2022-11-14T06:48:59Z" finished-at="2022-11-14T06:49:54Z">
      <class name="test.script.Sample">
        <test-method status="PASS" signature="configureSuite(org.testng.ITestContext)[pri:0, instance:test.script.Sample@32c4e8b2]" name="configureSuite" is-config="true" duration-ms="26" started-at="2022-11-14T06:48:59Z" finished-at="2022-11-14T06:48:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7734da3e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureSuite -->
        <test-method status="PASS" signature="processTestContext(org.testng.ITestContext)[pri:0, instance:test.script.Sample@32c4e8b2]" name="processTestContext" is-config="true" duration-ms="2" started-at="2022-11-14T06:48:59Z" finished-at="2022-11-14T06:48:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7734da3e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- processTestContext -->
        <test-method status="FAIL" signature="InitialTestSetupClass(org.testng.ITestContext)[pri:0, instance:test.script.Sample@32c4e8b2]" name="InitialTestSetupClass" is-config="true" duration-ms="54697" started-at="2022-11-14T06:48:59Z" finished-at="2022-11-14T06:49:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7734da3e]]>
              </value>
            </param>
          </params>
          <exception class="java.io.FileNotFoundException">
            <message>
              <![CDATA[E:\Automationframework\SharedFolder\SharedFolder\src\test\resources\Chrome\maps\null (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.FileNotFoundException: E:\Automationframework\SharedFolder\SharedFolder\src\test\resources\Chrome\maps\null (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileReader.<init>(Unknown Source)
at uiauto.lib.loader.JsonLoader.<init>(JsonLoader.java:18)
at uiauto.page.BasePage.setLoader(BasePage.java:79)
at uiauto.page.BasePage.<init>(BasePage.java:69)
at pages.LoginPage.<init>(LoginPage.java:12)
at tests.InitialTestSetup.InitialTestSetupClass(InitialTestSetup.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.FileNotFoundException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitialTestSetupClass -->
        <test-method status="FAIL" signature="startApplication(java.lang.reflect.Method)[pri:0, instance:test.script.Sample@32c4e8b2]" name="startApplication" is-config="true" duration-ms="1" started-at="2022-11-14T06:49:54Z" finished-at="2022-11-14T06:49:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.script.Sample.homePageDisplayed() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at uiauto.test.BaseTest.createReport(BaseTest.java:232)
at uiauto.test.BaseTest.createReport(BaseTest.java:227)
at uiauto.test.BaseTest.startApplication(BaseTest.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApplication -->
        <test-method status="SKIP" signature="homePageDisplayed()[pri:0, instance:test.script.Sample@32c4e8b2]" name="homePageDisplayed" duration-ms="0" started-at="2022-11-14T06:49:54Z" finished-at="2022-11-14T06:49:54Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at uiauto.test.BaseTest.createReport(BaseTest.java:232)
at uiauto.test.BaseTest.createReport(BaseTest.java:227)
at uiauto.test.BaseTest.startApplication(BaseTest.java:119)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageDisplayed -->
        <test-method status="FAIL" signature="tearDown(org.testng.ITestResult)[pri:0, instance:test.script.Sample@32c4e8b2]" name="tearDown" is-config="true" duration-ms="0" started-at="2022-11-14T06:49:54Z" finished-at="2022-11-14T06:49:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=Sample.homePageDisplayed()[pri:0, instance:test.script.Sample@32c4e8b2] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at uiauto.test.BaseTest.onException(BaseTest.java:182)
at uiauto.test.BaseTest.writeToReport(BaseTest.java:151)
at uiauto.test.BaseTest.tearDown(BaseTest.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:536)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="killAppiumServer()[pri:0, instance:test.script.Sample@32c4e8b2]" name="killAppiumServer" is-config="true" duration-ms="0" started-at="2022-11-14T06:49:54Z" finished-at="2022-11-14T06:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- killAppiumServer -->
      </class> <!-- test.script.Sample -->
    </test> <!-- Chrome -->
  </suite> <!-- Suite -->
</testng-results>
